### ISSUE TITLE
3. Meta Features

### ISSUE THREAD

**Issue by chez8990** [chez8990/kaggle_hateful_comments#2]
Meta features in text classification are non-text features. 
- [ ] Length of the text 
- [ ] Number of words
- [ ] Number of curse words 
- [ ] Number of punctuations
- [ ] Number named entities 
- [ ] Sentence sentiment 
- [ ] Number of capitalized words (defined to be words that are entirely consisted of capital letters)
- [ ] Predictions from other models during stacking
